// <auto-generated />
namespace Projeto_Liga_Tabajara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Inicial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202504160223172_Inicial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
